export const AVAILABLE_PLACES = [
	{ id: "p1", title: "Forest Waterfall", image: { src: "/assets/forest-waterfall.jpg", alt: "A tranquil forest waterfall" } },
	{ id: "p2", title: "Sahara Desert Dunes", image: { src: "/assets/desert-dunes.jpg", alt: "Golden desert dunes" } },
	{ id: "p3", title: "Majestic Mountains", image: { src: "/assets/majestic-mountains.jpg", alt: "Snow-capped peaks" } },
	{ id: "p4", title: "Caribbean Beach", image: { src: "/assets/caribbean-beach.jpg", alt: "Turquoise Caribbean beach" } },
	{ id: "p5", title: "Ancient Grecian Ruins", image: { src: "/assets/ruins.jpg", alt: "Historic ruins" } },
	{ id: "p6", title: "Amazon Rainforest Canopy", image: { src: "/assets/rainforest.jpg", alt: "Lush rainforest canopy" } },
	{ id: "p7", title: "Northern Lights", image: { src: "/assets/northern-lights.jpg", alt: "Aurora borealis" } },
	{ id: "p8", title: "Japanese Temple", image: { src: "/assets/japanese-temple.jpg", alt: "Ancient Japanese temple" } },
	{ id: "p9", title: "Great Barrier Reef", image: { src: "/assets/great-barrier-reef.jpg", alt: "Colorful coral reef" } },
	{ id: "p10", title: "Parisian Streets", image: { src: "/assets/parisian-streets.jpg", alt: "Charming Paris streets" } },
	{ id: "p11", title: "Grand Canyon", image: { src: "/assets/grand-canyon.jpg", alt: "Expansive Grand Canyon" } },
	{ id: "p12", title: "Venetian Canals", image: { src: "/assets/venetian-canals.jpg", alt: "Venice canals at sunset" } },
	{ id: "p13", title: "Taj Mahal", image: { src: "/assets/taj-mahal.jpg", alt: "The Taj Mahal" } },
	{ id: "p14", title: "Kerala Backwaters", image: { src: "/assets/kerala-backwaters.jpg", alt: "Kerala backwaters" } },
	{ id: "p15", title: "African Savanna", image: { src: "/assets/african-savanna.jpg", alt: "Savanna wildlife" } },
	{ id: "p16", title: "Victoria Falls", image: { src: "/assets/victoria-falls.jpg", alt: "Powerful waterfalls" } },
	{ id: "p17", title: "Machu Picchu", image: { src: "/assets/machu-picchu.jpg", alt: "Historic Machu Picchu" } },
	{ id: "p18", title: "Amazon River", image: { src: "/assets/amazon-river.jpg", alt: "Amazon river" } },
];
